

# Team we're interested in (see team_list.txt for a list of all options)
TEAM = ESP



#-------------------------------------------------------------------------
# 					Paths you may want to edit
#-------------------------------------------------------------------------

# Most of these have to do with the locations and names of files.
# If you change the structure of the directory or rename a file,
# you might have to change something here.


# 
# Paths to data files
# 

# Path to all data (relative to the directory the Makefile resides in)
DATA_PATH = data

# Path to the pdfs and basic CSVs they generate
RAW_PATH = $(DATA_PATH)/$(YEAR)/$(SEX)/raw

# Path to the processed files (those derived from the tables extracted from the pdfs)
PROCESSED_PATH = $(DATA_PATH)/$(YEAR)/$(SEX)/processed

# File containing which teams played in which game that year
GAME_LIST_FILE = $(PROCESSED_PATH)/team-game_pairings.csv

# File containing all the teams that played in the tournament that year
TEAM_LIST_FILE = $(PROCESSED_PATH)/team_list.txt

# File containing all actions for a given team
ALL_ACTIONS_FILE = $(PROCESSED_PATH)/$(TEAM)/all_actions.csv

# File containing all shots for a given team
SHOTS_FILE = $(PROCESSED_PATH)/$(TEAM)/shots.csv

# File containing shot summary for a team
SHOT_SUMMARY_FILE = $(PROCESSED_PATH)/$(TEAM)/shot_summary.csv



# 
# Python script names/locations
# 

# Path to the python scripts (relative to the directory the Makefile resides in)
PY_PATH = .

# Name of the script that pulls the tables from the pdfs
EXTRACT_TABLES_SRC = $(PY_PATH)/extract_tables.py

# Name of the script that converts CSV files to JSON
CONVERT_TO_JSON_SRC = $(PY_PATH)/convert_to_json.py

# Name of the script that aggregates all the data corresponding to a team
GROUP_BY_TEAM_SRC = $(PY_PATH)/group_by_team.py

# Name of the script that splits up the Action column into
# "Action," "Result," and "Goal"
SPLIT_ACTION_COL_SRC = $(PY_PATH)/split_action_column.py

# Name of the script that generates shot summaries for players on a team
SHOT_SUMMARY_SRC = $(PY_PATH)/generate_shot_summary.py


# 
# Internet paths
# 

# The url for the water polo games (needs to be completed with game#$(PDF_TYPE))
# Not used for anything yet
BASE_URL = http://waterpolo.sportresult.com/pdf/WCH$(YEAR)/$(SEX)

#-------------------------------------------------------------------------
# 			Parameters you almost certainly don't need to worry about
#-------------------------------------------------------------------------

# The names of the pdfs
PDF_FILES = $(wildcard $(RAW_PATH)/*.pdf)

# The names of the CSV files generated by extract_tables.py
CSV_FILES = $(patsubst $(RAW_PATH)/%.pdf, %.csv, $(PDF_FILES))